### ISSUE TITLE
Home page carousel does not appear

### ISSUE THREAD

**Issue by johngriffin** [atchai/newsverify#1]
An item has been added to the nodequeue:
http://opennewsplatform.atchai.com/admin/structure/nodequeue/1/view/1

Carousel does not appear on front page:
http://opennewsplatform.atchai.com/

Home page context places the block.  The view seems to be pulling the content correctly from the nodequeue.

**Comment by robhardwick** [comment]
The demo site wasn't fully up-to-date so it was still exhibiting this bug. I've updated to the latest version and everything should now be working.

**Comment by kae76** [comment]
tested:

Carousel does appear on front page:
http://opennewsplatform.atchai.com/
